global:
  resolve_timeout: 1m

route:
  receiver: 'mail'
  repeat_interval: 1h
  group_by: [ alertname ]

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.email.com:587'
        auth_username: 'alertmanager@email.com'
        auth_password: 'password'
        from: 'alertmanager@email.com'
        to: 'your@email.com'
